/**
 * Benchmark tagging — two competing schemes the user can compare side by side.
 *
 *  scheme "ability"  — the 10 operationalized cognitive abilities from
 *                      Benchmark Profiling (arXiv:2510.01232), plus domain
 *                      helper tags. Bottom-up: what skill does the task stress?
 *  scheme "survey"   — the benchmark taxonomy from Figure 2 of "A Survey on
 *                      LLM Benchmarks" (arXiv:2508.15361). Top-down: where does
 *                      the benchmark sit in the field's category tree?
 *
 * Each benchmark is tagged under BOTH schemes (data/benchmark-tags.json), so the
 * profiling page can toggle between them. Assignments are generated by
 * scripts/tag-benchmarks.ts.
 */

export interface TagDef {
  id: string;
  label: string;
  group: string;
  description: string;
}

export interface TagGroupDef {
  id: string;
  label: string;
  tags: TagDef[];
}

export interface TagScheme {
  id: "ability" | "survey";
  label: string;
  paper: string;
  url: string;
  blurb: string;
  groups: TagGroupDef[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Scheme 1 — Profiling abilities (arXiv:2510.01232)
// ─────────────────────────────────────────────────────────────────────────────
const ABILITY_TAGS: TagDef[] = [
  { id: "analogical", label: "Analogical Reasoning", group: "ability", description: "Mapping relational patterns rather than surface similarity (A:B :: C:?)." },
  { id: "commonsense-causal", label: "Commonsense & Causal", group: "ability", description: "Inferring plausible causes, effects, or next events in everyday scenarios." },
  { id: "contextual-recall", label: "Contextual Recall", group: "ability", description: "Retrieving verbatim details from a passage — short-term textual memory." },
  { id: "deductive", label: "Deductive Reasoning", group: "ability", description: "Deriving conclusions from premises via logical rules and steps." },
  { id: "inductive", label: "Inductive Reasoning", group: "ability", description: "Discovering patterns in sequences and extrapolating to new cases." },
  { id: "knowledge-recall", label: "Long-Term Knowledge", group: "ability", description: "Retrieving stored factual knowledge absent from the prompt." },
  { id: "quantitative", label: "Quantitative Reasoning", group: "ability", description: "Numerical word problems, arithmetic, multi-step math operations." },
  { id: "semantic-comprehension", label: "Semantic Comprehension", group: "ability", description: "Understanding roles and relations among entities, explicit and implicit." },
  { id: "spatial-geometric", label: "Spatial & Geometric", group: "ability", description: "Positions, directions, shapes, distances, mental maps." },
  { id: "temporal", label: "Temporal Reasoning", group: "ability", description: "Sequence, simultaneity, and duration of events." },
];

const DOMAIN_TAGS: TagDef[] = [
  { id: "coding", label: "Coding", group: "domain", description: "Program synthesis, bug-fixing, software engineering." },
  { id: "math", label: "Mathematics", group: "domain", description: "Competition math, proofs, quantitative problem sets." },
  { id: "multilingual", label: "Multilingual", group: "domain", description: "Evaluated across multiple natural languages." },
  { id: "korean", label: "Korean", group: "domain", description: "Korean-language benchmark." },
  { id: "chinese", label: "Chinese", group: "domain", description: "Chinese-language benchmark." },
  { id: "safety", label: "Safety", group: "domain", description: "Refusal, jailbreak, bias, harmful-content evaluation." },
  { id: "multimodal", label: "Multimodal", group: "domain", description: "Image, chart, document, or video understanding." },
  { id: "agentic", label: "Agentic / Tool-Use", group: "domain", description: "Multi-step tool use and environment interaction." },
  { id: "long-context", label: "Long Context", group: "domain", description: "Reasoning over very long inputs." },
  { id: "factuality", label: "Factuality", group: "domain", description: "Factual accuracy and hallucination resistance." },
  { id: "instruction-following", label: "Instruction Following", group: "domain", description: "Adhering to explicit format / constraint instructions." },
  { id: "medical", label: "Medical / Health", group: "domain", description: "Clinical knowledge and medical QA." },
  { id: "preference", label: "Human Preference", group: "domain", description: "Open-ended quality judged by humans or an LLM." },
  { id: "robustness", label: "Robustness", group: "domain", description: "Contamination-resistant or perturbation stress tests." },
];

export const SCHEME_ABILITY: TagScheme = {
  id: "ability",
  label: "Profiling Abilities",
  paper: "Benchmark Profiling",
  url: "https://arxiv.org/abs/2510.01232",
  blurb: "10 cognitive abilities (+ domain helpers). Bottom-up: which skill the task stresses.",
  groups: [
    { id: "ability", label: "Abilities", tags: ABILITY_TAGS },
    { id: "domain", label: "Domains", tags: DOMAIN_TAGS },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Scheme 2 — Survey taxonomy (arXiv:2508.15361, Figure 2)
//
// Unlike scheme 1's flat ability bag, this is a *hierarchy* — the field's
// category tree (like biological ranks). A benchmark is classified into one or
// more LEAF nodes; its full path up the tree is its taxonomy. Selecting an
// internal node in the explorer selects its whole subtree.
// ─────────────────────────────────────────────────────────────────────────────
export interface TaxNode {
  id: string;
  label: string;
  description?: string;
  children?: TaxNode[];
}

export const SURVEY_TREE: TaxNode[] = [
  {
    id: "general", label: "General Capabilities",
    children: [
      { id: "linguistic", label: "Linguistic Core", description: "NLU, generation, dialogue, multilingual, holistic." },
      { id: "knowledge", label: "Knowledge", description: "Comprehensive / expert / exam / language-specific knowledge." },
      { id: "reasoning", label: "Reasoning", description: "Logical, commonsense, causal, mathematical, applied reasoning." },
    ],
  },
  {
    id: "domain", label: "Domain-Specific",
    children: [
      {
        id: "natural-sciences", label: "Natural Sciences",
        children: [
          { id: "mathematics", label: "Mathematics", description: "Math problem solving as a subject." },
          { id: "physics", label: "Physics" },
          { id: "chemistry", label: "Chemistry" },
          { id: "biology", label: "Biology / Medicine", description: "Biology and clinical/medical evaluation (PubMedQA, LAB-Bench…)." },
          { id: "cross-science", label: "Cross-Disciplinary", description: "GPQA, TheoremQA, SciEval, WMDP, OpenBookQA." },
        ],
      },
      {
        id: "humanities", label: "Humanities & Social Sci",
        children: [
          { id: "law", label: "Law" },
          { id: "ip", label: "Intellectual Property" },
          { id: "education", label: "Education" },
          { id: "psychology", label: "Psychology" },
          { id: "finance", label: "Finance" },
        ],
      },
      {
        id: "engineering", label: "Engineering & Technology",
        children: [
          { id: "code-gen", label: "Code Generation", description: "HumanEval, MBPP, LiveCodeBench, BigCodeBench…" },
          { id: "code-maintenance", label: "Code Maintenance & Repair", description: "SWE-bench, repair, debug, editing." },
          { id: "code-understanding", label: "Code Understanding", description: "CruxEval, RepoBench, CodeXGLUE." },
          { id: "database-devops", label: "Database & DevOps", description: "Text-to-SQL, Spider, BIRD, OpsEval." },
          { id: "hardware", label: "Hardware & Engineering", description: "VerilogEval, RTLLM, CIRCUIT." },
        ],
      },
    ],
  },
  {
    id: "target", label: "Target-Specific",
    children: [
      {
        id: "risk", label: "Risk & Reliability",
        children: [
          { id: "safety-t", label: "Safety", description: "Jailbreak, refusal, toxicity, bias." },
          { id: "hallucination", label: "Hallucination", description: "TruthfulQA, SimpleQA, FActScore…" },
          { id: "robustness-t", label: "Robustness", description: "IFEval, AdvGLUE, perturbation." },
          { id: "data-leak", label: "Data Leak", description: "Contamination / memorization resistance." },
        ],
      },
      {
        id: "agent-grp", label: "Agent",
        children: [
          { id: "agent-planning", label: "Planning & Control", description: "BrowseComp, WebWalker, Mobile-Bench." },
          { id: "multi-agent", label: "Multi-Agent" },
          { id: "agent-integrated", label: "Integrated & Holistic", description: "GAIA, AgentBench, τ-bench, TravelPlanner." },
          { id: "agent-domain", label: "Domain-Specific Agent", description: "OSWorld, MCP, finance/science agents." },
          { id: "agent-safety", label: "Agent Safety", description: "AgentHarm, SafeAgentBench, R-Judge." },
        ],
      },
      { id: "others", label: "Others", description: "JudgeBench, OR-Bench, RouterBench, etc." },
    ],
  },
];

export const SCHEME_SURVEY: Pick<TagScheme, "id" | "label" | "paper" | "url" | "blurb"> = {
  id: "survey",
  label: "Survey Taxonomy",
  paper: "A Survey on LLM Benchmarks",
  url: "https://arxiv.org/abs/2508.15361",
  blurb: "Field taxonomy tree (계>문>강 식 계층). Top-down: where the benchmark sits.",
};

// ── Tree helpers ─────────────────────────────────────────────────────────────
const SURVEY_NODE_BY_ID = new Map<string, TaxNode>();
const SURVEY_PARENT = new Map<string, string | null>();
(function index(nodes: TaxNode[], parent: string | null) {
  for (const n of nodes) {
    SURVEY_NODE_BY_ID.set(n.id, n);
    SURVEY_PARENT.set(n.id, parent);
    if (n.children) index(n.children, n.id);
  }
})(SURVEY_TREE, null);

export function isSurveyLeaf(id: string): boolean {
  const n = SURVEY_NODE_BY_ID.get(id);
  return !!n && !n.children;
}

/** All leaf ids beneath a node (or the node itself if it's a leaf). */
export function surveyDescendantLeaves(id: string): string[] {
  const n = SURVEY_NODE_BY_ID.get(id);
  if (!n) return [];
  if (!n.children) return [id];
  return n.children.flatMap((c) => surveyDescendantLeaves(c.id));
}

export const SURVEY_LEAF_IDS: string[] = SURVEY_TREE.flatMap((n) =>
  surveyDescendantLeaves(n.id),
);

/** Labels from root → leaf, e.g. ["Domain-Specific","Natural Sciences","Mathematics"]. */
export function surveyPath(leafId: string): string[] {
  const out: string[] = [];
  let cur: string | null = leafId;
  while (cur) {
    const n = SURVEY_NODE_BY_ID.get(cur);
    if (n) out.unshift(n.label);
    cur = SURVEY_PARENT.get(cur) ?? null;
  }
  return out;
}

export const SCHEMES = {
  ability: SCHEME_ABILITY,
  survey: SCHEME_SURVEY,
} as const;

export type SchemeId = "ability" | "survey";

const ALL_BY_ID = new Map<string, TagDef>();
for (const g of SCHEME_ABILITY.groups) for (const t of g.tags) ALL_BY_ID.set(t.id, t);

/** Resolve any tag/leaf id to a label (works for both schemes). */
export function tagById(id: string): TagDef | undefined {
  const a = ALL_BY_ID.get(id);
  if (a) return a;
  const n = SURVEY_NODE_BY_ID.get(id);
  if (n) return { id: n.id, label: n.label, group: "survey", description: n.description ?? "" };
  return undefined;
}

/** Valid tag ids of a scheme — used by the generator to validate output.
 *  For survey this is the leaf set. */
export function schemeTagIds(id: SchemeId): Set<string> {
  if (id === "ability") {
    return new Set(SCHEME_ABILITY.groups.flatMap((g) => g.tags.map((t) => t.id)));
  }
  return new Set(SURVEY_LEAF_IDS);
}
